### ISSUE TITLE
Lookup by mixed case `subtag`

### ISSUE THREAD

**Issue by AmitMY** [mattcg/language-tags#11]
```ts
tags.subtags('Sgnw')
```
Should return the same as
```ts
tags.subtags('sgnw')
```

Which is 
![image](https://user-images.githubusercontent.com/5757359/154771437-b2c94e1e-5bd8-4bf4-beb0-9421141cdd31.png)

**Comment by mattcg** [comment]
Better late than never :)

**Comment by AmitMY** [comment]
Thank you!
