### ISSUE TITLE
license compatibility issue

### ISSUE THREAD

**Issue by Yaniv-Ozerzon** [mattcg/language-tags#13]
Hi,
I am concerned about a license compatibility issue. The license for this project is MIT, but one of the dependencies ([language-subtag-registry](https://github.com/mattcg/language-subtag-registry)) is under a strong copyleft license ([Open Data Commons Attribution License (ODC-BY)](http://opendatacommons.org/licenses/by/1.0/)). This copyleft license affects the creation of any Collective/Derivative Database. I have some concerns about using this project as it may affect any downstream database without knowing.
I would very much appreciate your assistance.

**Comment by mattcg** [comment]
Thanks for bringing this up. You're not the first to do so and it's about time we did something about it. Tracking the issue in mattcg/language-subtag-registry/issues/8.

**Comment by mattcg** [comment]
Switched to CC0 1.0

**Comment by and-poulsen** [comment]
@mattcg, you'll then also need to update the version of language-subtag-registry dependency in this package to v0.3.23, otherwise it's still detected as using the previous ODC-BY

**Comment by mattcg** [comment]
ah! Good catch. Done.
