### ISSUE TITLE
Getting lint error in latest version of language-tags 

### ISSUE THREAD

**Issue by manju-s** [mattcg/language-tags#15]
Hey Matt,
After the release of version 1.0.6 eslint is picking up a Syntax error which is casuing our build to fail (screenshot below).
When i lock the version to 1.0.5, the error goes away. Can you please look into it, or suggest a fix if it can be done from the consumer side.
Thanks
<img width="992" alt="image" src="https://user-images.githubusercontent.com/60998582/205277436-3973b6a2-db41-497b-81e4-1be4d5ee4ce6.png">

**Comment by mattcg** [comment]
Hi manju, thanks for filing. I'm not really sure why this is an issue because [static class fields](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/Public_class_fields) are part of the ECMAScript standard. It seems that jshint is missing support for them even though they're standard. See: jshint/jshint/issues/3139

In the meantime it might make sense to exclude `/node_modules` from your linter.

**Comment by enkhtulga** [comment]
Any update for it? How to resolve it?

**Comment by enkhtulga** [comment]
@manju-s  did you resolve the issue?

**Comment by mattcg** [comment]
I added an eslint config block to the package config file and bumped the version to 1.0.7 on npm. Can you retest? I no longer get any errors with `eslint lib/`.

**Comment by manju-s** [comment]
> I added an eslint config block to the package config file and bumped the version to 1.0.7 on npm. Can you retest? I no longer get any errors with `eslint lib/`.

<img width="997" alt="image" src="https://user-images.githubusercontent.com/60998582/207834148-b6f877d7-b285-4017-8992-fbc633cc92f7.png">
Still getting the same error Matt

**Comment by mattcg** [comment]
I guess that's because your linter isn't picking up the block in `language-tags/package.json`.

Shouldn't your linter configuration be ignoring the `node_modules/` directory? Sure you only want to lint your own code and not that of third party modules?

Alternatively, if you also want to lint `node_modules/`, you'll have to set `"ecmaVersion": 13` in your eslint configuration.

Unless you do that, there's nothing more I can do to fix this issue.

**Comment by manju-s** [comment]
> I guess that's because your linter isn't picking up the block in `language-tags/package.json`.
> 
> Shouldn't your linter configuration be ignoring the `node_modules/` directory? Sure you only want to lint your own code and not that of third party modules?
> 
> Alternatively, if you also want to lint `node_modules/`, you'll have to set `"ecmaVersion": 13` in your eslint configuration.
> 
> Unless you do that, there's nothing more I can do to fix this issue.

Yes Matt, node_modules is added in eslintignore but for some reason it isn't working. Anyway, thanks for the help, please update if any additional fixes are made.

**Comment by afc163** [comment]
https://github.com/cnpm/bug-versions/pull/217/files

language-tags 1.0.6 and 1.0.7 cannot work on node version like 1.0.5. Is it a better way to release a major version?

**Comment by mattcg** [comment]
Which nodejs version are you saying it doesn’t work in?

**Comment by ljharb** [comment]
@mattcg this is a breaking change in a patch version. v1.0.5 works in node 6; v1.0.6 does not (for example, becuase of the spread operator - babel could fix this for you). This breaks eslint-plugin-jsx-a11y.

Can you please publish a v1.0.8 that restores these node versions, and if you like, publish a v2 that drops them?

**Comment by ljharb** [comment]
ping @mattcg; there's still a breaking change in a patch version in v1.0.6 and v1.0.7.

**Comment by mattcg** [comment]
Wait, why would anyone be running node 6?

**Comment by ljharb** [comment]
All of my packages support as far back as possible, most down to node 0.4, but that’s irrelevant - semver applies to engine support. If you want to drop node 6 in a major, that’s fine, but not in a patch.

**Comment by mattcg** [comment]
Makes sense. How do you recommend to fix this?

**Comment by ljharb** [comment]
I suspect if you adjust your babel config to target the lowest version of node that language-tags v1 supports - which since it lacks an engines declaration, is basically 0.4 or 0.6 - that it'd Just Work without any source code changes.

**Comment by ljharb** [comment]
@mattcg are you interested in a PR for this? eslint-plugin-jsx-a11y is still pinned to v1.0.5.

**Comment by mattcg** [comment]
Yes. For sure!On 12 Aug 2023, at 00:35, Jordan Harband ***@***.***> wrote:﻿
@mattcg are you interested in a PR for this? eslint-plugin-jsx-a11y is still pinned to v1.0.5.

**Comment by ljharb** [comment]
@mattcg awesome! first is #17; once that's landed i'll put up one that adds babel.

**Comment by ljharb** [comment]
#17 → #18 → #19
