### ISSUE TITLE
`.valid('hy-Latn-IT-arevela')` returns false

### ISSUE THREAD

**Issue by QuestionAndAnswer** [mattcg/language-tags#16]
`hy-Latn-IT-arevela` listed as an example of a valid string, but the library returns false, instead of expected true.

https://www.rfc-editor.org/rfc/rfc5646#page-80

**Comment by QuestionAndAnswer** [comment]
Never mind, I printed errors and found `arevela` was depricated. 
Duplicate of: https://github.com/mattcg/language-tags/issues/6

**Comment by mattcg** [comment]
Thanks for reporting either way. You reminded me that I need to fix #6...
