### ISSUE TITLE
Valid combinations of subtags

### ISSUE THREAD

**Issue by rawnsley** [mattcg/language-tags#20]
Is there anything in the standard that describes which combinations of subtags are valid? The question is the same as this [SO post](https://stackoverflow.com/questions/75115584/are-all-combinations-of-language-codes-and-regions-in-the-language-subtag-regist), but what I would actually like to do is to enumerate all of the valid **language**-**region** combinations (and possibly add **script** into the mix) so I can store them in a SQL enum column efficiently.

I appreciate that this a standards question rather than applying to this library in particular, but you are the most accessible authority on RFC 5646 :-)

**Comment by mattcg** [comment]
hi @rawnsley. It's technically possible to enumerate all the combinations but 1) you would have hundreds of thousands of them, way more than can fit in an enum 2) tags and subtags change often so it doesn't make sense to change your db schema every time.
