### ISSUE TITLE
Cannot read properties of undefined (reading 'toLowerCase')

### ISSUE THREAD

**Issue by mmick66** [mattcg/language-tags#24]
It seems that if I call the `language` function with `undefined`, it simply breaks. This should be protected and return `null` just as if it were the string `"abracatabra"`.

```typescript
import * as tags from 'language-tags';
tags.language(undefined);
```
throws an error 
```bash
Cannot read properties of undefined (reading 'toLowerCase')
```

**Comment by mmick66** [comment]
@mattcg Is there a release for that?

**Comment by mattcg** [comment]
I just published v2.0.0 because I made a breaking change (for Node < 20) to ES modules syntax for the source, though the lib which is generated using babel should still be compatible with Node >= 10).

**Comment by mmick66** [comment]
Wow, I hope my comment was not the only thing that warranted a **major** version update!

**Comment by mattcg** [comment]
haha! No, it was because I migrated the codebase to ES6 modules from CommonJS. So no new features but since it could make it incompatible for some using the source on pre-2023 nodejs I thought a major version bump was warranted.

**Comment by mmick66** [comment]
Great! Now I'm getting the import error? So... how do you import it now? 

I am using NodeJS `v20.17.0` and importing it like so
```typescript
import * as tags from 'language-tags';
```
It's throwing an error 
```bash
Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/michailmichailidis/Projects/mathpro-backend/node_modules/language-tags/lib/index.js from /Users/michailmichailidis/Projects/mathpro-backend/src/seeders/tests-from-origin.seeder.ts not supported.
index.js is treated as an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which declares all .js files in that package scope as ES modules.
Instead either rename index.js to end in .cjs, change the requiring code to use dynamic import() which is available in all CommonJS modules, or change "type": "module" to "type": "commonjs" in /Users/michailmichailidis/Projects/mathpro-backend/node_modules/language-tags/package.json to treat all .js files as CommonJS (using .mjs for all ES modules instead).
```

**Comment by mattcg** [comment]
I dropped support for Babel as it was driving me crazy. Try 2.0.1. You'll need to use ES6 imports.
