### ISSUE TITLE
Let search function rank equal description at top.

### ISSUE THREAD

**Issue by MartijnR** [mattcg/language-tags#4]
When performing `tags.search('Dari')`, it would be great if we can get the the language with subtag 'prs' returned at the top of the results. It is currently 7th.

The first result in the array is a language with description _Alviri-Vidari_. 

I'm wondering if one way of doing this would be to check the initial results for a result with a description that (case-insensitively) is equal to the search description. If found, make that the first result.

Just a thought. It can also be done outside the library of course and I would understand that ranking could eventually become very complex.

**Comment by mattcg** [comment]
Thanks for reporting this @MartijnR. I actually think that this isn't that hard to do. Since we're matching on the exact phrase and not tokenising then probably a good way to match is using the description string length. The shorter the string the more likely it is to be at the top.

**Comment by MartijnR** [comment]
That's a cool idea. It seems that data.record. Description is an array with multiple items though. So sorting by string-length may mean you have to re-match to find which description matched?

Just FYI, I've implemented it like this now (I couldn't get a sorting function to work properly):

``` js
function _getLangWithDesc( desc ) {
    var results = tags.search( desc ).filter( _languagesOnly );
    var exactMatch = results.filter( function( obj ) {
        return obj.data.record.Description.some( function( description ) {
            return description.toLowerCase() === desc.toLowerCase();
        } );
    } )[ 0 ];

    return exactMatch || results[ 0 ];
}
```

It's not very efficient. It should actually use `some` instead of `filter`.

**Comment by mattcg** [comment]
Will you try master please? I've pushed some changes.

**Comment by MartijnR** [comment]
Works like a charm! :+1: 

I like dealing with cases like this ("Dari" returning fewer results than "dari").

Thanks!

**Comment by MartijnR** [comment]
Would it be possible to publish the latest version on npm?

**Comment by mattcg** [comment]
@MartijnR done :)

**Comment by MartijnR** [comment]
Thanks!

**Comment by MartijnR** [comment]
Small remaining issue:

tags.search('English') returns the language with tag "gyn" (Guyanese Creole English) at the top of the list

Changing [line 72](https://github.com/mattcg/language-tags/blob/master/lib/index.js#L72) to:
     `return description.toLowerCase() === query;`
and [line 76](https://github.com/mattcg/language-tags/blob/master/lib/index.js#L76) to:
      `return description === query;`
seems to resolve it.

**Comment by mattcg** [comment]
Fixed! Thanks for reporting.

**Comment by MartijnR** [comment]
:+1: Thanks!
