### ISSUE TITLE
.valid() function bugged

### ISSUE THREAD

**Issue by paddotk** [mattcg/language-tags#7]
Hi,

I'm trying to check some IETF tags for validity and notice that the `.valid()` function does not return correct output at all. For example, when I check the following: `languageTags('nl-UA').valid()` it returns true, while the combination of `nl` (Dutch) and `UA` (Ukraine) should clearly be false.
It looks like any combination of two separately valid language and region tags are considered to be valid.

**Comment by simlu** [comment]
I'm not sure that is actually what you want. Clients can generate these combinations, so treating them as valid might be desirable.

**Comment by paddotk** [comment]
Doesn't that defy the idea of a validity check? I don't see why someone would want a non-existing combination such as `nl-UA` to be considered valid.
If clients merely want to check for the right structure they could simply use a regex such as `/[a-z]{2}-[A-Z]{2,13}/` (I know this regex doesn't exactly match all IETF tags, but just for example's sake). I myself at least, would expect a `valid()` function to actually check the list of existing tags.

**Comment by mattcg** [comment]
Hi @paddotk, thanks for reporting this. I understand your expectation and perhaps `valid()` is not the best name for this function as it's really a comprehensive syntax check, that also checks whether each subtag in the tag is actually registered.

However there is no way that I'm aware of to check whether a syntactically valid combination of registered subtags is actually in use, like `nl-UA` for example. How can we know, programmatically, whether there's a variant of Dutch spoken in Ukraine or not?

**Comment by simlu** [comment]
@paddotk If that's what you want I'd recommend maintaining your own list in a file and checking against that. Lists to get started with can be found online.

However that's where we were coming from and we found that clients do generate weird, non existing combinations. We still want to do localization to the best of our abilities, even if the client tag is not an "official" combination. Hence we just switched to this library.

Would you mind explaining your use case? Why do you want to do a strict check? I.e. why would you want to fail if the phone resides in Italy but the selected language is English?

**Comment by paddotk** [comment]
@mattcg From what I understood before from the readme, the [language-subtag-registry](https://github.com/mattcg/language-subtag-registry) repo is used for all the data on possible locales, and therefore I thought that these JSON files were used for lookups on whether a tag exists/is valid or not.
I understand now that it's not exactly that. Yet, would a lookup in these registry JSON files be a good way to check for validity perhaps?

@simlu In our application, our users upload pdf files and have to indicate the locale (used OCR/text recognition and machine learning). This doesn't work properly when only a language without, or with an incorrect, region tag. Therefore we want to avoid non-existing combinations to be used.

**Comment by mattcg** [comment]
Hi @paddotk, it does do a lookup of the registry, but the registry contains subtags not tags (with a few exceptions). For example, it contains `en` and `US` but not `en-US`. Therefore we can only know whether tags are syntactically valid i.e. whether they use registered subtags in the right order, and not whether the combination is one that's used in everyday life.

In your case, since you're doing OCR and there's only a limited number of tags that the software understands, I'd simply whitelist those tags and not use this library.

**Comment by paddotk** [comment]
@mattcg Thanks for clearing that up. We ended up finding a list with all possible combinations so all is good :)

**Comment by mattcg** [comment]
Great, I’m glad!
